import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule } from '@angular/common/http';
import { registerLocaleData } from '@angular/common';
import en from '@angular/common/locales/en';
import { NZ_I18N, en_US } from 'ng-zorro-antd/i18n';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CoreModule } from './core/core.module';
import { LayoutModule } from './layout/layout.module';
import { NzIconModule } from 'ng-zorro-antd/icon';

// Import specific icons for tree-shaking
import {
  HomeOutline,
  SecurityScanOutline,
  BookOutline,
  DatabaseOutline,
  SafetyOutline,
  BarChartOutline,
  FileDoneOutline,
  KeyOutline,
  DashboardOutline,
  PullRequestOutline,
  SettingOutline,
  SafetyCertificateOutline,
  SolutionOutline,
  ToolOutline,
  FileSearchOutline,
  ControlOutline,
  MonitorOutline,
  CloudServerOutline,
  HddOutline,
  ReconciliationOutline,
  IdcardOutline,
  ScanOutline,
  LockOutline,
  TeamOutline,
  BankOutline,
  MailOutline,
  EyeOutline,
  SyncOutline,
  ImportOutline,
  CheckSquareOutline,
  QuestionCircleOutline,
  UserOutline,
  AppstoreOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  BellOutline,
  DownOutline,
  LogoutOutline,
  FileTextOutline,
  WarningOutline,
  GlobalOutline,
  DesktopOutline,
  ExperimentOutline,
  ThunderboltOutline,
  SwapOutline,
  AuditOutline,
  LineChartOutline,
  PieChartOutline,
  CodeOutline,
  FundOutline,
  StockOutline,
  BranchesOutline,
  CheckCircleOutline,
  MessageOutline,
  ApartmentOutline,
  UserAddOutline,
  EditOutline,
  GroupOutline,
  ContainerOutline,
  ScheduleOutline,
  RocketOutline,
  ClusterOutline,
  FundProjectionScreenOutline,
  RadarChartOutline,
  RobotOutline,
  UnorderedListOutline,
  PlusOutline,
  DownloadOutline,
  ExceptionOutline,
  MoreOutline,
  SearchOutline,
  ReloadOutline,
  FolderOutline,
  FileOutline,
  CaretUpFill,
  CaretDownFill,
  CaretRightOutline,
  CloseCircleOutline,
  FilterOutline,
  PlusCircleOutline,
  DeleteOutline,
  ExportOutline,
  MinusCircleOutline,
  ArrowLeftOutline,
  CloseOutline,
  ClockCircleOutline,
  InfoCircleOutline,
  CopyOutline,
  EyeInvisibleOutline,
  UnlockOutline,
  StopOutline,
  WifiOutline,
  SendOutline,
  SaveOutline,
  ApiOutline,
  CloudOutline,
  CloudUploadOutline,
  UploadOutline,
  RightOutline,
  PictureOutline,
  SnippetsOutline,
  HistoryOutline,
  PlayCircleOutline,
  ExclamationCircleOutline,
  UserDeleteOutline,
  DisconnectOutline,
  LinkOutline,
  NumberOutline,
  UpOutline,
  SelectOutline,
  InboxOutline,
  StepForwardOutline,
  CheckCircleFill,
  ArrowUpOutline,
  ArrowDownOutline,
  PoweroffOutline,
  UndoOutline,
  FileExcelOutline,
  PlusSquareOutline,
  DoubleRightOutline,
  DoubleLeftOutline,
  LeftOutline,
  ReadOutline,
  ColumnHeightOutline,
  MinusSquareOutline,
  EnterOutline,
  FieldTimeOutline,
  FallOutline,
  DollarOutline,
  SlidersOutline,
  FullscreenOutline,
  ShopOutline,
  ArrowRightOutline,
  BugOutline,
  CaretDownOutline,
  CaretUpOutline,
  CheckOutline,
  ClearOutline,
  CloseSquareOutline,
  CloudSyncOutline,
  CustomerServiceOutline,
  FastForwardOutline,
  HolderOutline,
  InfoOutline,
  OrderedListOutline,
  PaperClipOutline,
  ProfileOutline,
  PartitionOutline,
  PauseOutline,
  FileProtectOutline,
  NodeExpandOutline,
  NodeCollapseOutline,
  TableOutline,
} from '@ant-design/icons-angular/icons';

registerLocaleData(en);

const icons = [
  HomeOutline, SecurityScanOutline, BookOutline, DatabaseOutline, SafetyOutline,
  BarChartOutline, FileDoneOutline, KeyOutline, DashboardOutline, PullRequestOutline,
  SettingOutline, SafetyCertificateOutline, SolutionOutline, ToolOutline, FileSearchOutline,
  ControlOutline, MonitorOutline, CloudServerOutline, HddOutline,
  ReconciliationOutline, IdcardOutline, ScanOutline, LockOutline, TeamOutline,
  BankOutline, MailOutline, EyeOutline, SyncOutline, ImportOutline,
  CheckSquareOutline, QuestionCircleOutline, UserOutline, AppstoreOutline,
  MenuFoldOutline, MenuUnfoldOutline, BellOutline, DownOutline, LogoutOutline,
  FileTextOutline, WarningOutline, GlobalOutline, DesktopOutline, ExperimentOutline,
  ThunderboltOutline, SwapOutline, AuditOutline, LineChartOutline, PieChartOutline,
  CodeOutline, FundOutline, StockOutline, BranchesOutline, CheckCircleOutline,
  MessageOutline, ApartmentOutline, UserAddOutline, EditOutline, GroupOutline,
  ContainerOutline, ScheduleOutline, RocketOutline, ClusterOutline,
  FundProjectionScreenOutline, RadarChartOutline, RobotOutline, UnorderedListOutline,
  PlusOutline, DownloadOutline, ExceptionOutline, MoreOutline, SearchOutline,
  ReloadOutline, FolderOutline, FileOutline,
  CaretUpFill, CaretDownFill, CaretRightOutline, CloseCircleOutline, FilterOutline,
  PlusCircleOutline, DeleteOutline, ExportOutline, MinusCircleOutline,
  ArrowLeftOutline, CloseOutline, ClockCircleOutline, InfoCircleOutline,
  CopyOutline, EyeInvisibleOutline, UnlockOutline, StopOutline,
  WifiOutline, SendOutline, SaveOutline, ApiOutline,
  CloudOutline, CloudUploadOutline, UploadOutline, RightOutline, PictureOutline, SnippetsOutline,
  HistoryOutline, PlayCircleOutline, ExclamationCircleOutline,
  UserDeleteOutline, DisconnectOutline, LinkOutline, NumberOutline, UpOutline,
  SelectOutline, InboxOutline, StepForwardOutline, CheckCircleFill,
  ArrowUpOutline, ArrowDownOutline, PoweroffOutline,
  UndoOutline, FileExcelOutline, PlusSquareOutline,
  DoubleRightOutline, DoubleLeftOutline, LeftOutline, ReadOutline,
  ColumnHeightOutline, MinusSquareOutline, EnterOutline, FieldTimeOutline,
  FallOutline, DollarOutline, SlidersOutline, FullscreenOutline, ShopOutline,
  ArrowRightOutline, BugOutline, CaretDownOutline, CaretUpOutline, CheckOutline,
  ClearOutline, CloseSquareOutline, CloudSyncOutline, CustomerServiceOutline,
  FastForwardOutline, HolderOutline, InfoOutline, OrderedListOutline,
  PaperClipOutline, ProfileOutline,
  PartitionOutline, PauseOutline, FileProtectOutline,
  NodeExpandOutline, NodeCollapseOutline, TableOutline,
];

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutingModule,
    CoreModule,
    LayoutModule,
    NzIconModule.forRoot(icons),
  ],
  providers: [
    { provide: NZ_I18N, useValue: en_US },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
